version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ubiquitous-lang-postgres
    environment:
      POSTGRES_DB: ubiquitous_lang_db
      POSTGRES_USER: ubiquitous_lang_user
      POSTGRES_PASSWORD: ubiquitous_lang_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - ubiquitous-lang-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ubiquitous-lang-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ubiquitous-lang.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - ubiquitous-lang-network
    restart: unless-stopped

  smtp4dev:
    image: rnwood/smtp4dev:v3
    container_name: ubiquitous-lang-smtp4dev
    ports:
      - "5080:80"    # Web UI
      - "2525:25"    # SMTP Port
    networks:
      - ubiquitous-lang-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  ubiquitous-lang-network:
    driver: bridge